// AUTOGENERATED by scripts/extract-9slice-blackjack.js — do not edit by hand.
// Regenerate by running: npm run extract:dice-blackjack-9slice
import convexUrl from 'assets/end_card/Button_Convex.png';

export interface NineSliceBorders {
  left: number;
  top: number;
  right: number;
  bottom: number;
}

export interface NineSliceAsset {
  url: string;
  border: NineSliceBorders;
}

export const buttons9slice: Record<string, NineSliceAsset> = {
  convex: {
    url: convexUrl,
    border: { left: 20, top: 20, right: 20, bottom: 28 },
  },
};
