// Shared "Layer Lab Convex Rectangle" button — the SINGLE source of truth for the
// chunky octagonal CTA used across the project (dice-blackjack PostGame Claim/Double
// buttons AND the end-card Play-Now button). The 9-slice texture + border live in
// the autogenerated `buttons9slice.ts` alongside this file; callers load that
// texture and pass it in (this module imports NO assets, so it stays unit-testable).
import { Container, NineSliceSprite, Text, TextStyle, Texture } from 'pixi.js';
import type { NineSliceBorders } from './buttons9slice';

/**
 * Canonical "fun mobile game" cartoon-caps font stack. One definition, imported
 * everywhere a game-display caption is drawn (no per-file string copies).
 */
export const GAME_FONT_STACK = '"Luckiest Guy", Impact, "Arial Black", sans-serif';

export interface ConvexTint {
  /** Multiplied onto the gray-baseline texture for the raised face. */
  face: number;
  /** Multiplied onto the recess sitting under the face (the "pocket"). */
  pocket: number;
  /** Optional outer glow tint (e.g. the Double-or-nothin' button). */
  glow?: number;
}

/**
 * Tint palette for the convex texture (gray-baseline → multiplied at runtime, so the
 * texture's own gradient + outline + gloss carry through and only the hue shifts).
 * `face` is the resting color, `pocket` the dark recess beneath, `glow` the rim halo.
 */
export const CONVEX_TINTS = {
  /** Green Claim / Play-Now CTA. */
  cta: { face: 0x4bd66a, pocket: 0x0c3014 },
  /** Purple Double-or-nothin' with a cyan glow. */
  challenge: { face: 0xc44ad6, pocket: 0x270930, glow: 0x6ef0ff },
} as const;

/**
 * Resolve once the Luckiest Guy webfont has parsed, so the first Pixi Text isn't
 * cached with the fallback glyphs. The @font-face itself is registered by importing
 * the bundled `fonts.css` (a webpack side-effect import done in the scene, not here —
 * this module stays asset-free and unit-testable). Degrades gracefully (resolves
 * immediately) where the FontFace API is unavailable (e.g. the node test harness).
 */
let gameFontReady: Promise<void> | null = null;
export function ensureGameFontLoaded(): Promise<void> {
  if (gameFontReady) return gameFontReady;
  const docFonts = (globalThis as { document?: { fonts?: { load?: (f: string) => Promise<unknown> } } }).document?.fonts;
  if (!docFonts || typeof docFonts.load !== 'function') {
    gameFontReady = Promise.resolve();
    return gameFontReady;
  }
  gameFontReady = docFonts
    .load('40px "Luckiest Guy"')
    .then(() => undefined)
    .catch(() => undefined);
  return gameFontReady;
}

/** White cartoon caption with a dark outline — the convex button label style. */
export function convexLabelStyle(fontSize: number): TextStyle {
  return new TextStyle({
    fill: 0xffffff,
    fontFamily: GAME_FONT_STACK,
    fontSize,
    stroke: { color: 0x181008, width: Math.max(3, Math.round(fontSize * 0.16)), join: 'round' },
  });
}

/** A NineSliceSprite of the convex texture at the given size (corners stay crisp). */
export function makeConvexSlice(
  texture: Texture,
  border: NineSliceBorders,
  w: number,
  h: number,
): NineSliceSprite {
  const sprite = new NineSliceSprite({
    texture,
    leftWidth: border.left,
    topHeight: border.top,
    rightWidth: border.right,
    bottomHeight: border.bottom,
  });
  sprite.width = w;
  sprite.height = h;
  return sprite;
}

export interface ConvexButtonOptions {
  texture: Texture;
  border: NineSliceBorders;
  width: number;
  height: number;
  label: string;
  fontSize: number;
  /** Defaults to the green CTA palette. */
  tint?: ConvexTint;
}

export interface ConvexButtonParts {
  /** Outer container (positioned by the caller; interactivity wired by the caller). */
  root: Container;
  /** Press-feedback target — slides down into the pocket on pointerdown. */
  face: Container;
  /** Centered caption (held so callers can retext it, e.g. coin amounts). */
  label: Text;
}

/**
 * Assemble a convex button: a dark pocket recess, a tinted raised face on top, and
 * a centered Luckiest-Guy caption. Both slices are cut from the SAME passed texture.
 * Origin is the button center, so the caller positions `root` at the target point.
 */
export function createConvexButton(opts: ConvexButtonOptions): ConvexButtonParts {
  const tint = opts.tint ?? CONVEX_TINTS.cta;
  const { texture, border, width, height } = opts;

  const root = new Container();

  const pocket = makeConvexSlice(texture, border, width, height);
  pocket.tint = tint.pocket;
  pocket.position.set(-width / 2, -height / 2);
  root.addChild(pocket);

  const face = new Container();
  root.addChild(face);

  const faceSprite = makeConvexSlice(texture, border, width, height);
  faceSprite.tint = tint.face;
  faceSprite.position.set(-width / 2, -height / 2);
  face.addChild(faceSprite);

  const label = new Text({ text: opts.label, style: convexLabelStyle(opts.fontSize) });
  label.anchor.set(0.5);
  face.addChild(label);

  return { root, face, label };
}
